# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Aprendiz de todo
paginate:       5
baseurl:        ""
url:            "http://blog.robotchrist.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Nando Sola
  url:          http://blog.robotchrist.com
  email:        nando.sola@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
